# Generated by Django 3.1.2 on 2020-12-13 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=50)),
                ('fileType', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=20)),
                ('fileObject', models.FileField(upload_to='C:\\Code\\contentUploader\\media/')),
                ('fileFormat', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('fileResolution', models.IntegerField(default=360)),
                ('insertedAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
