# Generated by Django 3.1.2 on 2020-12-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentUploaderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileSize',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
